<#
Generates a Markdown summary of commits and file changes for each calendar day in a range.

Usage:
  pwsh scripts/agent_history_md.ps1
  pwsh scripts/agent_history_md.ps1 -StartDate "2025-12-04" -EndDate "2025-12-12" -Output "agent_history_summary.md"
The end date is exclusive.
#>
[CmdletBinding()]
param(
  [string]$StartDate = "2025-12-04",
  [string]$EndDate = "2025-12-12",
  [string]$Output = "agent_history_summary.md"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $utf8NoBom
$OutputEncoding = $utf8NoBom

$PSDefaultParameterValues["Out-File:Encoding"]   = "utf8"
$PSDefaultParameterValues["Set-Content:Encoding"] = "utf8"
$PSDefaultParameterValues["Add-Content:Encoding"] = "utf8"

function Get-TopArea {
  param([Parameter(Mandatory = $true)][string]$Path)
  $first = ($Path -replace "^\.\\", "") -split "[/\\]" | Select-Object -First 1
  if (-not $first) { return "other" }
  switch ($first.ToLowerInvariant()) {
    "backend"   { "backend" }
    "frontend"  { "frontend" }
    "infra"     { "infra" }
    "docs"      { "docs" }
    "scripts"   { "scripts" }
    "desktop"   { "desktop" }
    "data"      { "data" }
    "binaries"  { "binaries" }
    ".github"   { "ci" }
    default     { "other" }
  }
}

function Get-DateStrict {
  param([string]$Value)
  [datetime]::ParseExact($Value, "yyyy-MM-dd", [System.Globalization.CultureInfo]::InvariantCulture)
}

function Invoke-GitUtf8 {
  param([Parameter(Mandatory = $true)][string[]]$Args)
  $gitArgs = @(
    "-c","i18n.logOutputEncoding=utf-8",
    "-c","i18n.commitEncoding=utf-8",
    "-c","core.quotepath=false"
  ) + $Args
  $out = & git @gitArgs
  if ($LASTEXITCODE -ne 0) {
    throw ("git failed: git " + ($Args -join " "))
  }
  return $out
}

$start = Get-DateStrict -Value $StartDate
$end = Get-DateStrict -Value $EndDate

if ($start -ge $end) {
  throw "StartDate ($StartDate) must be before EndDate ($EndDate)."
}

$days = @()
$fileStatsMap = @{}

for ($d = $start; $d -lt $end; $d = $d.AddDays(1)) {
  $dNext = $d.AddDays(1)
  $since = $d.ToString("yyyy-MM-dd")
  $until = $dNext.ToString("yyyy-MM-dd")

  $hashes = Invoke-GitUtf8 -Args @("log", "--since=$since", "--until=$until", "--pretty=format:%H")

  $commitEntries = @()
  foreach ($hash in $hashes) {
    if ([string]::IsNullOrWhiteSpace($hash)) { continue }

    $files = Invoke-GitUtf8 -Args @("show", "--name-only", "--pretty=", $hash)

    $fileEntries = @()
    foreach ($file in $files) {
      if ([string]::IsNullOrWhiteSpace($file)) { continue }

      $area = Get-TopArea -Path $file

      $contentString = ""
      try {
        $content = Invoke-GitUtf8 -Args @("show", $hash, "--", $file)
        $contentString = ($content -join "`n")
      } catch {
        $contentString = "<content unavailable: git show failed>"
      }

      $fileEntries += [ordered]@{
        path    = $file
        area    = $area
        content = $contentString
      }

      if (-not $fileStatsMap.ContainsKey($file)) {
        $fileStatsMap[$file] = @{ count = 0; area = $area }
      }
      $fileStatsMap[$file].count++
    }

    $commitEntries += [ordered]@{
      hash  = $hash
      files = $fileEntries
    }
  }

  $days += [ordered]@{
    date    = $since
    commits = $commitEntries
  }
}

$fileStats = $fileStatsMap.GetEnumerator() |
  Sort-Object Name |
  ForEach-Object {
    [ordered]@{
      path  = $_.Key
      area  = $_.Value.area
      count = $_.Value.count
    }
  }

$summary = [ordered]@{
  startDate = $start.ToString("yyyy-MM-dd")
  endDate   = $end.ToString("yyyy-MM-dd")
  days      = $days
  fileStats = $fileStats
}

$sb = [System.Text.StringBuilder]::new()
$rangeLabel = "$($summary.startDate) to $($summary.endDate) (end exclusive)"
$totalCommits = ($summary.days | ForEach-Object { $_.commits.Count } | Measure-Object -Sum).Sum

$null = $sb.AppendLine("# Agent History ($rangeLabel)")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("Generated by scripts/agent_history_md.ps1. Commit count: $totalCommits.")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("## Daily Activity")
$null = $sb.AppendLine("")

foreach ($day in $summary.days) {
  $null = $sb.AppendLine("### $($day.date)")
  if ($day.commits.Count -eq 0) {
    $null = $sb.AppendLine("- No commits.")
    $null = $sb.AppendLine("")
    continue
  }

  foreach ($commit in $day.commits) {
    $null = $sb.AppendLine("- Commit ``$($commit.hash)``")
    if ($commit.files.Count -eq 0) {
      $null = $sb.AppendLine("  - No files changed.")
      continue
    }

    $null = $sb.AppendLine("  - Files:")
    foreach ($file in $commit.files) {
      $null = $sb.AppendLine("    - [$($file.area)] $($file.path)")
      if (-not [string]::IsNullOrEmpty($file.content)) {
        $null = $sb.AppendLine('      ```')
        $null = $sb.AppendLine($file.content)
        $null = $sb.AppendLine('      ```')
      }
    }
    $null = $sb.AppendLine("")
  }

  $null = $sb.AppendLine("")
}

$null = $sb.AppendLine("## File Change Totals")
$null = $sb.AppendLine("")
if ($summary.fileStats.Count -eq 0) {
  $null = $sb.AppendLine("- No file changes in range.")
} else {
  $null = $sb.AppendLine("| Path | Area | Count |")
  $null = $sb.AppendLine("| --- | --- | --- |")
  foreach ($stat in $summary.fileStats) {
    $null = $sb.AppendLine("| $($stat.path) | $($stat.area) | $($stat.count) |")
  }
}

[System.IO.File]::WriteAllText($Output, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote markdown summary to $Output"
